#
# MIT License
#
# (C) Copyright 2023-2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Cray-HPE/CMS-core-testing"
    labels:
      - "github-actions-deps"
      - "dependabot"
    open-pull-requests-limit: 16

  - package-ecosystem: "gomod"
    directory: "/cmsdev" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "Cray-HPE/CMS-core-testing"
    labels:
      - "go-deps"
      - "dependabot"
    open-pull-requests-limit: 16
    groups:
      k8s:
        patterns: [ "k8s.io/*" ]
      protobuf:
        patterns: [ "github.com/golang/protobuf", "google.golang.org/protobuf" ]
    allow:
      # Allow updates to both direct and indirect dependencies
      - dependency-type: "all"
    ignore:
      # Only look for patch version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "k8s.io/*"
        versions: [ ">=0.25.0" ]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Cray-HPE/CMS-core-testing"
    labels:
      - "python-deps"
      - "dependabot"
    open-pull-requests-limit: 16
    allow:
      # Allow updates to both direct and indirect dependencies
      - dependency-type: "all"
    ignore:
      # Only look for patch version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]
