#!/bin/sh
#
# Copyright 2020, Cray Inc.

UPLOAD_FILE=$1
PVC_HOST=`kubectl get pods -n services -l app.kubernetes.io/instance=cms-ipxe -o custom-columns=NS:.metadata.name --no-headers`
PVC_PATH="/shared_tftp"

usage()
{
  echo "Usage:"
  echo "$0: <upload-file>"
}

if [ -z $UPLOAD_FILE ]; then
    echo "No file given to upload. Exiting."
    usage
    exit 1
fi

if [ -f $UPLOAD_FILE ]; then
    echo "Uploading file: $UPLOAD_FILE"
    kubectl cp $UPLOAD_FILE services/$PVC_HOST:$PVC_PATH
else
    echo "$UPLOAD_FILE is not a file. Exiting."
    exit 1
fi
if [ $? -ne 0 ]; then
    echo "Failed to upload $UPLOAD_FILE - error code = $?"
    exit $?
else
    echo "Successfully uploaded $UPLOAD_FILE!"
fi
