#!/bin/sh
#
# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# (MIT License)

UPLOAD_FILE=$1
PVC_HOST=`kubectl get pods -n services -l app.kubernetes.io/instance=cms-ipxe -o custom-columns=NS:.metadata.name --no-headers`
PVC_PATH="/shared_tftp"

usage()
{
  echo "Usage:"
  echo "$0: <upload-file>"
}

if [ -z $UPLOAD_FILE ]; then
    echo "No file given to upload. Exiting."
    usage
    exit 1
fi

if [ -f $UPLOAD_FILE ]; then
    echo "Uploading file: $UPLOAD_FILE"
    kubectl cp $UPLOAD_FILE services/$PVC_HOST:$PVC_PATH
else
    echo "$UPLOAD_FILE is not a file. Exiting."
    exit 1
fi
if [ $? -ne 0 ]; then
    echo "Failed to upload $UPLOAD_FILE - error code = $?"
    exit $?
else
    echo "Successfully uploaded $UPLOAD_FILE!"
fi
